name: Build and Release Web

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: PWD
        run: pwd

      - uses: subosito/flutter-action@v1
        with:
          channel: "beta"

      - name: Install dependencies
        run: flutter pub get

      - name: Analyzing project
        run: flutter analyze

      - name: Enable web support
        run: flutter config --enable-web

      - name: Build web app
        run: flutter build web

      - name: Copy files
        run: cp -R /home/runner/work/garen_gui/garen_gui/build/web /home/runner/work/garen_gui/garen_gui/docs